---
title: "Class Objectives-Zee"
format: docx
editor: source
---

## Goals of this document

We will treat this class more like a job. There will not be tests or quizzes. Rather we will have conversations where we discuss how you are doing, and what you could improve on. You will reflect on your work, I will reply and we will discuss your grade from there.

We can discuss amendment of objectives as well, especially your personal objectives.

## Basic objectives

Over the course it is expected you will:

**Technically**

1.  Understand and implement the basic R-Studio -\> GitHub workflow; be able to collaborate using GitHub.
2.  Work in Quarto files; be able to adjust format and make output look nice.
3.  Complete https://swcarpentry.github.io/r-novice-gapminder/index.html
4.  Develop slideshow and website.
5.  Use code to further your own research.

**Communications**

1.  Provide respectful feedback in class and on Slack.
2.  Assist with issues on in class and on Slack.



## Personal objectives

* find cellular data to analyze and visualize
    * consider https://datacarpentry.org/genomics-r-intro/
    * https://bioconductor.github.io/BiocWorkshops/r-and-bioconductor-for-everyone-an-introduction.html
    
* make workflowr website https://workflowr.github.io/workflowr/

**Reflection**
Looking back at my time in the R coding class, I started with no background in coding, which made the beginning especially challenging. Despite feeling overwhelmed at first, I committed myself to fully engage with the class by doing all my homework and putting in extra effort to understand the concepts like watching youtube videos just to learn/understand some concepts and i remember after first day of class I was like what is this! i started watching beginner tutorials for R lol, and also my friend is doing a PHD in engineering and he uses R for his work/research! and he showed me some of his work on R and I found that interesting for me to do for later when I start working on my own research (BTW if you haven't gotten all of my homework on github you can ask to see them during our meetings because maybe some of them were not pushed to github)

So From being unsure about coding to reaching a point where I'm now comfortable with R shows how far I've come. I've come to realize that in coding, there's no final level of expertise or being perfect rather it's a continuous journey of learning. Every challenge I faced pushed me to learn more. and yep i kept on asking you a lot of questions to solve some of the challenges i've faced (thanks for not making me feel like I was trying to debug my brain out loud!)

Anyway, I know there are students in the class who came with prior experience with R, I've focused on my own growth. Seeing my improvement and knowing the effort I've put into learning R, and comparing me to others who maybe more experts in R, I feel a grade of B+ represents my journey. 



